### ISSUE TITLE
Homepage - Welcome: image is not aligned with the sidebar form compared to the desing 

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Civil-and-General-Distributors#64]
![image](https://cloud.githubusercontent.com/assets/17717843/15203156/86877daa-1833-11e6-8662-2850b064d279.png)

**Comment by iteano** [comment]
Not fixed. There's still a slight misalignment at the bottom.

**Comment by maehtitan** [comment]
@ganesh-titan Not yet fixed in 481px to 1199px view port sizes.

**Comment by maehtitan** [comment]
@ganesh-titan Issues still recurring to all browsers.
**IE and Microsoft Edge - Form is shorter.**
![image](https://cloud.githubusercontent.com/assets/13363508/15697788/27d94672-27f0-11e6-9bc7-0dc8ebd1e7b5.png)

**Opera ang Chrome - Video layout is shorter.**
![image](https://cloud.githubusercontent.com/assets/13363508/15697795/407e61d0-27f0-11e6-95b5-a820888e24a2.png)

**It is only fixed in Firefox only**
![image](https://cloud.githubusercontent.com/assets/13363508/15697814/682841ce-27f0-11e6-9687-e1bdd1cb65d9.png)
